[project]
name = "scs"
version = "0.1.0"
description = "Smart Customer Service"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.127.0",
    "langchain>=1.2.0",
    "langchain-community>=0.4.0",
    "langchain-openai>=1.1.0",
    "uvicorn>=0.40.0",
]
